#!/bin/bash

#DEBHELPER#

# postrm script for plymouth-modified-init

#set -e

case "$1" in
  purge|remove) dpkg-divert --quiet                                               \
                            --remove                                              \
                            --package plymouth-modified-init               \
                            --rename       \
                            --divert /etc/init.d/plymouth.dpkg-distrib \
                            /etc/init.d/plymouth
                            
                   dpkg-divert --quiet                                               \
                               --remove                                                 \
                               --package plymouth-modified-init            \
                               --rename                              \
                               --divert /usr/lib/systemd/system/plymouth-halt.service.dpkg-distrib \
                               /usr/lib/systemd/system/plymouth-halt.service
                               
                   dpkg-divert --quiet                                               \
                               --remove                                                 \
                               --package plymouth-modified-init            \
                               --rename                              \
                               --divert /usr/lib/systemd/system/plymouth-poweroff.service.dpkg-distrib \
                               /usr/lib/systemd/system/plymouth-poweroff.service
                               
                   dpkg-divert --quiet                                               \
                               --remove                                                 \
                               --package plymouth-modified-init            \
                               --rename                              \
                               --divert /usr/lib/systemd/system/plymouth-reboot.service.dpkg-distrib \
                               /usr/lib/systemd/system/plymouth-reboot.service
                ;;

             *) :
                ;;
esac 

exit 0
